### ISSUE TITLE
please update to html-minifier which fixes uglify-js vulnerabilities

### ISSUE THREAD

**Issue by bonesoul** [lackneets/express-beautify#1]
more information here: https://github.com/kangax/html-minifier/issues/598#issuecomment-205124603

**Comment by bonesoul** [comment]
any updates?

**Comment by bonesoul** [comment]
for anyone interested i've published a new package with the dependency updates;

https://www.npmjs.com/package/express-beautifier

**Comment by lackneets** [comment]
Sorry to be late for months, package is now updated. 
Thanks for your interim version, I prefer to keep original package name
